import type { Garment, Look } from "./types";

const now = "2026-09-01T12:00:00.000Z";

function g(
  partial: Omit<Garment, "archived" | "createdAt" | "wornOn" | "notes" | "brand" | "demo"> &
    Partial<Pick<Garment, "notes" | "brand" | "wornOn">>,
): Garment {
  return {
    archived: false,
    createdAt: now,
    notes: "",
    brand: "",
    wornOn: [],
    demo: true,
    ...partial,
  };
}

export const SEED_GARMENTS: Garment[] = [
  g({
    id: "g_oxford",
    name: "Navy oxford",
    category: "top",
    subtype: "oxford shirt",
    colors: ["navy"],
    material: "cotton",
    formality: 3,
    warmth: 2,
    seasons: ["spring", "fall", "winter"],
    imageSrc: "/garments/navy-oxford.jpg",
    cutoutSrc: "/garments/navy-oxford.jpg",
    imageSource: "official",
    matteQuality: "clean",
    brand: "closet",
  }),
  g({
    id: "g_polo",
    name: "Grey polo",
    category: "top",
    subtype: "polo",
    colors: ["grey"],
    material: "pique cotton",
    formality: 2,
    warmth: 2,
    seasons: ["spring", "summer", "fall"],
    imageSrc: "/garments/grey-polo.jpg",
    cutoutSrc: "/garments/grey-polo.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_tee",
    name: "White crew tee",
    category: "top",
    subtype: "t-shirt",
    colors: ["white"],
    material: "cotton",
    formality: 1,
    warmth: 1,
    seasons: ["spring", "summer", "fall"],
    imageSrc: "/garments/white-tee.jpg",
    cutoutSrc: "/garments/white-tee.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_cream",
    name: "Ivory crewneck",
    category: "top",
    subtype: "sweater",
    colors: ["ivory", "cream"],
    material: "merino",
    formality: 3,
    warmth: 4,
    seasons: ["fall", "winter"],
    imageSrc: "/garments/cream-knit.jpg",
    cutoutSrc: "/garments/cream-knit.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_vneck",
    name: "Navy merino",
    category: "top",
    subtype: "v-neck sweater",
    colors: ["navy"],
    material: "merino",
    formality: 3,
    warmth: 4,
    seasons: ["fall", "winter"],
    imageSrc: "/garments/navy-vneck.jpg",
    cutoutSrc: "/garments/navy-vneck.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_jeans",
    name: "Indigo jeans",
    category: "bottom",
    subtype: "jeans",
    colors: ["indigo"],
    material: "denim",
    formality: 2,
    warmth: 3,
    seasons: ["spring", "fall", "winter", "summer"],
    imageSrc: "/garments/indigo-jeans.jpg",
    cutoutSrc: "/garments/indigo-jeans.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_trousers",
    name: "Charcoal trousers",
    category: "bottom",
    subtype: "trousers",
    colors: ["charcoal"],
    material: "wool",
    formality: 4,
    warmth: 3,
    seasons: ["fall", "winter", "spring"],
    imageSrc: "/garments/charcoal-trousers.jpg",
    cutoutSrc: "/garments/charcoal-trousers.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_chinos",
    name: "Stone chinos",
    category: "bottom",
    subtype: "chinos",
    colors: ["khaki", "stone"],
    material: "cotton",
    formality: 2,
    warmth: 2,
    seasons: ["spring", "summer", "fall"],
    imageSrc: "/garments/khaki-chinos.jpg",
    cutoutSrc: "/garments/khaki-chinos.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_olive",
    name: "Olive overshirt",
    category: "outerwear",
    subtype: "overshirt",
    colors: ["olive"],
    material: "cotton twill",
    formality: 2,
    warmth: 3,
    seasons: ["spring", "fall"],
    imageSrc: "/garments/olive-overshirt.jpg",
    cutoutSrc: "/garments/olive-overshirt.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_coat",
    name: "Camel overcoat",
    category: "outerwear",
    subtype: "overcoat",
    colors: ["camel"],
    material: "wool",
    formality: 4,
    warmth: 5,
    seasons: ["fall", "winter"],
    imageSrc: "/garments/camel-coat.jpg",
    cutoutSrc: "/garments/camel-coat.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_sneakers",
    name: "White court sneakers",
    category: "footwear",
    subtype: "sneakers",
    colors: ["white"],
    material: "leather",
    formality: 1,
    warmth: 2,
    seasons: ["spring", "summer", "fall"],
    imageSrc: "/garments/white-sneakers.jpg",
    cutoutSrc: "/garments/white-sneakers.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_loafers",
    name: "Brown penny loafers",
    category: "footwear",
    subtype: "loafers",
    colors: ["brown"],
    material: "leather",
    formality: 3,
    warmth: 2,
    seasons: ["spring", "fall", "summer"],
    imageSrc: "/garments/brown-loafers.jpg",
    cutoutSrc: "/garments/brown-loafers.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_belt",
    name: "Brown leather belt",
    category: "accessory",
    subtype: "belt",
    colors: ["brown"],
    material: "leather",
    formality: 3,
    warmth: 1,
    seasons: ["spring", "summer", "fall", "winter"],
    imageSrc: "/garments/brown-belt.jpg",
    cutoutSrc: "/garments/brown-belt.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
  g({
    id: "g_cap",
    name: "Navy cap",
    category: "accessory",
    subtype: "cap",
    colors: ["navy"],
    material: "cotton",
    formality: 1,
    warmth: 2,
    seasons: ["spring", "summer", "fall"],
    imageSrc: "/garments/navy-cap.jpg",
    cutoutSrc: "/garments/navy-cap.jpg",
    imageSource: "official",
    matteQuality: "clean",
  }),
];

export const SEED_LOOKS: Look[] = [
  {
    id: "l_office",
    name: "Quiet office",
    occasion: "work",
    garmentIds: ["g_oxford", "g_trousers", "g_loafers", "g_belt"],
    source: "manual",
    createdAt: now,
  },
  {
    id: "l_weekend",
    name: "Saturday market",
    occasion: "weekend",
    garmentIds: ["g_polo", "g_jeans", "g_sneakers"],
    source: "manual",
    createdAt: now,
  },
  {
    id: "l_knit",
    name: "Ivory denim",
    occasion: "casual",
    garmentIds: ["g_cream", "g_jeans", "g_loafers"],
    source: "manual",
    createdAt: now,
  },
];
